{% set version = "0.3.1" %}

package:
  name: optima
  version: {{ version }}

source:
  url: https://github.com/reaktoro/optima/archive/v{{ version }}.tar.gz
  sha256: 52d32620090d9aeacb4a31ad1ce620d93df0ac54024905999c9876d29112aa0b
  
build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - ccache   # [unix]
    - clcache  # [win]
  host:
    - catch2 =2
    - eigen4rkt
    - python
    - numpy
    - eigen4rkt
    - pip
    - pybind11
    - pybind11-abi
    - pybind11-stubgen
    - setuptools
    - pytest
    - pytest-xdist
  run:
    - python
    - numpy
    - eigen4rkt
test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  imports:
    - optima

about:
  home: https://github.com/reaktoro/optima
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.md
  summary: A C++/Python library for linear and non-linear constrained optimization calculations
  
  description: |
    Optima is a general-purpose C++/Python library for solving linear and
    non-linear constrained optimization problems.
    
  doc_url: https://github.com/reaktoro/optima
  dev_url: https://github.com/reaktoro/optima

extra:
  recipe-maintainers:
    - allanleal
