{% set version = "0.2.6" %}

package:
  name: optima
  version: {{ version }}

source:
  url: https://github.com/reaktoro/optima/archive/v{{ version }}.tar.gz
  sha256: dfbc79b2bc0c7e72e74b676fd40922002075b0136f036754b2f963698403c828

  #  Use the config below to use a branch to test conda-forge builds without creating GitHub releases.
  #git_url: https://github.com/reaktoro/optima.git
  #git_rev: master
  
build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - ccache   # [unix]
    - clcache  # [win]
  host:
    - catch2
    - eigen4rkt
    - python
    - numpy
    - eigen4rkt
    - pip
    - pybind11
    - pybind11-abi
    - pybind11-stubgen
    - setuptools
    - pytest
    - pytest-xdist
  run:
    - python
    - numpy
    - eigen4rkt
test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  imports:
    - optima

about:
  home: https://github.com/reaktoro/optima
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.md
  summary: A C++/Python library for linear and non-linear constrained optimization calculations
  
  description: |
    Optima is a general-purpose C++/Python library for solving linear and
    non-linear constrained optimization problems.
    
  doc_url: https://github.com/reaktoro/optima
  dev_url: https://github.com/reaktoro/optima

extra:
  recipe-maintainers:
    - allanleal
